const optionsNearMe = [
  {
    id: 1,
    title: "Popular cuisines near me",
    list: [
      "Bakery food near me",
      "Beverages food near me",
      "Biryani food near me",
      "Burger food near me",
      "Cafe food near me",
      "Bakery food near me",
      "Beverages food near me",
      "Biryani food near me",
      "Burger food near me",
      "Cafe food near me",
      "Bakery food near me",
      "Beverages food near me",
      "Biryani food near me",
      "Burger food near me",
      "Cafe food near me",
    ],
  },
  {
    id: 2,
    title: "Popular restaurant types near me",
    list: [
      " Bakeries near me",
      "Beverage Shops near me",
      "Bhojanalya near me",
      "Cafés near me",
      "Casual Dining near me",
      "Dessert Parlors near me",
      "Dhabas near me",
      "Fine Dining near me",
      "Food Courts near me",
      "Food Trucks near me",
      "Kiosks near me",
      "Lounges near me",
      "Paan Shop near me",
      "Quick Bites near me",
      "Sweet Shops near me",
    ],
  },
  {
    id: 3,
    title: "Top Restaurant Chains",
    list: [
      "Bikanervala",
      "Burger King",
      "Burger Singh",
      "Dunkin' Donuts",
      "KFC",
      "McDonald's",
      "Pizza Hut",
      "WOW! Momo",
    ],
  },
  {
    id: 4,
    title: "Cities We Deliver To",
    list: [
      "Delhi",
      "NCR",
      "Kolkata",
      "Mumbai",
      "Bengaluru",
      "Pune",
      "Hyderabad",
      "Chennai",
      "Lucknow",
      "Kochi",
      "Jaipur",
      "Ahmedabad",
      "Chandigarh",
      "Goa",
      "Indore",
      "Gangtok",
      "Nashik",
      "Ooty",
      "Shimla",
      "Ludhiana",
      "Guwahati",
      "Amritsar",
      "Kanpur",
      "Allahabad",
      "Aurangabad",
      "Bhopal",
    ],
  },
];

export default optionsNearMe;
